name: snapfeed
description: Snapfeed is an interactive user feedback tool for Flutter apps. Its purely written in Dart and runs on Android, iOS, Desktop and the Web.
version: 0.1.0
author: snapfeed.dev <hey@snapfeed.dev>
homepage: https://snapfeed.dev

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  http_parser: ^3.1.0

dev_dependencies:
  lint: ^0.3.0
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/snapfeed/assets/images/default.png
    - packages/snapfeed/assets/images/logo_draw.png
    - packages/snapfeed/assets/images/pen.png

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
