name: Static Analysis

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    container:
      image: cirrusci/flutter:stable

    steps:
    - uses: actions/checkout@v1.2.0

    - name: Download dependencies
      run: sudo --preserve-env=PATH env flutter packages get
    - name: Check Formatting
      run: sudo --preserve-env=PATH env flutter pub run tool/reformat.dart
    - name: Analyze
      run: sudo --preserve-env=PATH env flutter analyze lib
